# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ['**']

name: build-R-packages


jobs:
  build:
    runs-on: macOS-latest

    env:
      REPO_URL: "https://packagemanager.rstudio.com/all/2021-12-29+Y3JhbiwyOjQ1MjYyMTU7NTA1NEIwRDA/src/contrib"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.3'

    - name: Check R version
      run: R.version
      shell: Rscript {0}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Cache virtual environment
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Download and build packages
      run: |
        python -VV
        python -m generate_package_list packages.txt ${{ env.REPO_URL }} --build

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: R Packages
#        path: "*.tgz"
#        retention-days: 1
