# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ['**']

name: build-R-packages


jobs:
  build:
    runs-on: macos-11

    env:
      REPO_SNAPSHOT_DATE: "2023-04-07"
      REPO_URL: "https://packagemanager.rstudio.com/cran/2023-04-07"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
  
    - name: tidy
      run: |
        sudo rm -rf /usr/local/lib/lib*
        sudo rm -rf /usr/local/include/*
        sudo rm -rf /usr/local/pkg/*

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.3'

    - name: Install R deps
      run: |
        sudo R --quiet -e "
          source('https://raw.githubusercontent.com/jonathon-love/R-mac-web/master/cran/bin/install.R')
          install.libs(c('fribidi', 'gsl', 'udunits', 'gdal', 'openssl', 'geos', 'protobuf'), os='darwin17')
        "
        sudo rsync -av --no-perms --no-owner --no-group /tmp/usr/local/ /usr/local

    - name: Check R version
      run: R.version
      shell: Rscript {0}


    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Cache virtual environment
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - name: Download Repo
      run: |
        mkdir -p ~/git/drat
        rsync -azP repo:${{ secrets.REPO_DIR }}/cran/${{ env.REPO_SNAPSHOT_DATE }}/ ~/git/drat

        # symlink src/contrib to the binary (some things expect a src)
        mkdir -p ~/git/drat/src
        ln -F -s ../bin/macosx/contrib/4.1 ~/git/drat/src/contrib

    - name: Install drat
      run: |
        R --quiet -e "install.packages('drat', repo='https://cran.r-project.org')"

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Download and build packages
      run: |
        python -VV
        python -m generate_package_list packages.txt ${{ env.REPO_URL }} ~/git/drat --build

    - name: Populate Repo
      run: |
        R --quiet -e "{ lapply(list.files(pattern='\\\\\\\\.tgz$'), drat::insertPackage); invisible(NULL) }"

    - name: Upload Repo
      run: rsync -azP --delete ~/git/drat/ repo:${{ secrets.REPO_DIR }}/cran/${{ env.REPO_SNAPSHOT_DATE }}

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: R Packages
#        path: "*.tgz"
#        retention-days: 1
