# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ['**']

name: build-linux


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_SNAPSHOT_DATE: "2023-04-07"
      REPO_URL: "https://packagemanager.rstudio.com/cran/2023-04-07"
      R_LIBS_USER: "~/R/jamovi"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install jamovi
      run: |
        sudo apt install flatpak
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install    --user -y flathub org.freedesktop.Platform//21.08
        flatpak install    --user -y flathub org.freedesktop.Sdk//21.08
        flatpak install    --user -y https://dl.flathub.org/build-repo/21296/org.jamovi.jamovi.flatpakref
        # flatpak install    --user -y flathub org.jamovi.jamovi

    #- name: Set up R
    #  uses: r-lib/actions/setup-r@v2

    - name: Add R
      run: |
        sudo echo 'flatpak run --devel org.jamovi.jamovi -R $@' >/usr/local/bin/R
        sudo chmod a+x /usr/local/bin/R

    - name: Check R version
      run: |
        R --version

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Add rename
      run: sudo apt update && sudo apt install -y rename

    - name: Cache virtual environment
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - name: Install drat
      run: |
        mkdir ~/R
        mkdir ~/R/jamovi
        R --quiet -e "install.packages('drat',repo='https://cran.r-project.org',lib='~/R/jamovi')"

    - name: Download Repo
      run: |
        mkdir -p ~/git/drat
        rsync -azP repo:${{ secrets.REPO_DIR }}/cran-linux/${{ env.REPO_SNAPSHOT_DATE }}/ ~/git/drat
        mkdir -p ~/git/drat/src
        mkdir -p ~/git/drat/src/contrib
        echo "" >>~/git/drat/src/contrib/PACKAGES

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Download and build packages
      run: |
        python -VV
        python -m generate_package_list packages.txt ${{ env.REPO_URL }} ~/git/drat --build
        
        rename 's/^(.*)_R_x86_64-pc-linux-gnu\.tar\.gz$/$1.tar.gz.tmp/' *_R_x86_64-pc-linux-gnu.tar.gz
        rm -rf *.tar.gz
        rename 's/^(.*)\.tmp/$1/' *.tar.gz.tmp

    - name: Populate Repo
      run: |
        R --quiet -e "{a<-list.files(pattern='\\\\.tar\\\\.gz$');print(a);lapply(a,drat::insertPackage);invisible(NULL)}"

    - name: Upload Repo
      run: rsync -azP --delete ~/git/drat/ repo:${{ secrets.REPO_DIR }}/cran-linux/${{ env.REPO_SNAPSHOT_DATE }}

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: R Packages
#        path: "*.tgz"
#        retention-days: 1
